#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Setup instructions.

See: https://packaging.python.org/en/latest/distributing.html
"""

# ======================================================================
# :: Future Imports (for Python 2)
from __future__ import (
    division, absolute_import, print_function)
# BUG in setuptools if import unicode_literals

# ======================================================================
# :: Python Standard Library Imports
import os  # Miscellaneous operating system interfaces
import re  # Regular expression operations
from codecs import open  # use a consistent encoding (in Python 2)

# ======================================================================
# :: Choice of the setup tools
from setuptools import setup
from setuptools import find_packages

# ======================================================================
# project specific variables
NAME = 'DCMPI'
VERSION_FILEPATH = os.path.join(NAME.lower(), '_version.py')
README_FILEPATH = 'README.rst'

# get the working directory for the setup script
CWD = os.path.realpath(os.path.dirname(__file__))

# get the long description from the README file
with open(os.path.join(CWD, README_FILEPATH), encoding='utf-8') as readme_file:
    LONG_DESCRIPTION_TEXT = readme_file.read()


# ======================================================================
def fix_version(
        version=None,
        source_filepath=VERSION_FILEPATH):
    """
    Fix version in source code.

    Args:
        version (str): version to be used for fixing the source code
        source_filepath (str): Path to file where __version__ is located

    Returns:
        version (str): the actual version text used
    """

    def dummy_version():
        return '0.0.0.0'

    if version is None:
        try:
            from setuptools_scm import get_version
        except ImportError:
            get_version = dummy_version
        version = get_version()

    if not os.path.isfile(source_filepath):
        version_template = \
            '#!/usr/bin/env python\n' \
            '# -*- coding: utf-8 -*-\n' \
            '"""Package version file."""\n' \
            '# This file is automatically generated by `fix_version()`' \
            ' in the setup script.\n' \
            '__version__ = \'{version}\'\n'.format(version=version)
        with open(source_filepath, 'wb') as io_file:
            io_file.write(version_template.encode('utf-8'))
    else:
        with open(source_filepath, 'rb') as io_file:
            source = io_file.read().decode('utf-8')
            source = re.sub(
                r"__version__ = '.*'",
                "__version__ = '{}'".format(version),
                source, flags=re.UNICODE)
        with open(source_filepath, 'wb') as io_file:
            io_file.write(source.encode('utf-8'))

    return version


# ======================================================================
# :: call the setup tool
setup(
    name=NAME.lower(),

    description='DICOM Preprocessing Interface.',
    long_description=LONG_DESCRIPTION_TEXT,

    version=fix_version(),

    url='https://bitbucket.org/norok2/' + NAME.lower(),

    author='Riccardo Metere',
    author_email='rick@metere.it',

    license='GPLv3+',

    # See https://pypi.python.org/pypi?%3Aaction=list_classifiers
    classifiers=[
        'Development Status :: 3 - Alpha',

        'Environment :: Console',
        'Environment :: Console :: Curses',
        'Environment :: Win32 (MS Windows)',
        'Environment :: X11 Applications',

        'Intended Audience :: Science/Research',
        'Intended Audience :: Healthcare Industry',
        'Intended Audience :: System Administrators',

        'Topic :: Scientific/Engineering',
        'Topic :: Scientific/Engineering :: Medical Science Apps.',
        'Topic :: System :: Archiving',
        'Topic :: System :: Systems Administration',
        'Topic :: System :: Monitoring',
        'Topic :: Utilities',

        'Operating System :: POSIX',
        'Natural Language :: English',
        'Operating System :: OS Independent',

        'License :: OSI Approved :: '
        'GNU General Public License v3 or later (GPLv3+)',

        'Programming Language :: Python',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 3',
    ],

    keywords='dicom dcm preprocessing',

    packages=find_packages(exclude=['contrib', 'docs', 'tests']),

    install_requires=[
        'appdirs', 'pydicom', 'pytk', 'blessed', 'dicom2nifti',
        'flyingcircus'
    ],

    setup_requires=['setuptools', 'setuptools_scm'],

    extras_require={
        'blessings': 'blessings',
    },

    package_data={
        'dcmpi': [
            'resources/icon.*',
            'report_templates/*.html',],
    },
    include_package_data=True,

    data_files=[('share/icons', ['artwork/dcmpi_logo.svgz'])],

    entry_points={
        'console_scripts': [
            'dcmpi=dcmpi.dcmpi_run:main',
            'dcmpi_tui=dcmpi.dcmpi_run:main_tui',
            'dcmpi_cli=dcmpi.dcmpi_run:main_cli',
            'dcmpi_gui=dcmpi.dcmpi_run:main_gui',

            'dcmpi_run=dcmpi.dcmpi_run:main',
            'dcmpi_run_tui=dcmpi.dcmpi_run:main_tui',
            'dcmpi_run_cli=dcmpi.dcmpi_run:main_cli',

            'dcmpi_explorer=dcmpi.dcmpi_explorer:main',
            'dcmpi_explorer_tui=dcmpi.dcmpi_explorer:main_tui',
            'dcmpi_explorer_cli=dcmpi.dcmpi_explorer:main_cli',

            'dcmpi_update=dcmpi.dcmpi_update:main',
            'dcmpi_monitor_folder=dcmpi.dcmpi_monitor_folder:main',

            'dcmpi__do_acquire_sources=dcmpi.do_acquire_sources:main',
            'dcmpi__do_sorting=dcmpi.do_sorting:main',
            'dcmpi__do_backup=dcmpi.do_backup:main',
            'dcmpi__get_info=dcmpi.get_info:main',
            'dcmpi__get_meta=dcmpi.get_meta:main',
            'dcmpi__get_nifti=dcmpi.get_nifti:main',
            'dcmpi__get_prot=dcmpi.get_prot:main',
            'dcmpi__get_report=dcmpi.do_report:main',
        ],
        'gui_scripts': [
            'dcmpi_gui=dcmpi.dcmpi_run:main_gui',
            'dcmpi_run_gui=dcmpi.dcmpi_run:main_gui',
            'dcmpi_explorer_gui=dcmpi.dcmpi_explorer:main_gui',
        ]
    },
)
